// <auto-generated />
namespace RestaurantManagement.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initialCreateDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialCreateDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202501040858562_initialCreateDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
